<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="MD-LAP-019" name="AutomationSuites.nativeApp.P0_TestCases" tests="2" failures="1" timestamp="05 Mar 2018 17:55:13 GMT" time="101.945" errors="1">
  <testcase name="addLead" time="101.943" classname="AutomationSuites.nativeApp.P0_TestCases">
    <failure type="java.lang.AssertionError" message="expected [AutoHL_GaTdt,] but found [AutoHL_GaTdt, ]">
      <![CDATA[java.lang.AssertionError: expected [AutoHL_GaTdt,] but found [AutoHL_GaTdt, ]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at frameworkLibrary.mobDriverConfig.assertEquals_Text(mobDriverConfig.java:340)at nativeApp.LeadsPage.verifyData_LeadsPage(LeadsPage.java:38)at AutomationSuites.nativeApp.P0_TestCases.addLead(P0_TestCases.java:42)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)at java.util.concurrent.FutureTask.run(Unknown Source)at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)at java.lang.Thread.run(Unknown Source)]]>
    </failure>
  </testcase> <!-- addLead -->
  <testcase name="results" time="0.002" classname="AutomationSuites.nativeApp.P0_TestCases">
    <error type="java.lang.Error" message="Unresolved compilation problem: 
	The method testResult(AppiumDriver&lt;?&gt;, ITestResult) in the type mobDriverConfig is not applicable for the arguments (ITestResult)
">
      <![CDATA[java.lang.Error: Unresolved compilation problem: The method testResult(AppiumDriver<?>, ITestResult) in the type mobDriverConfig is not applicable for the arguments (ITestResult)at AutomationSuites.nativeApp.P0_TestCases.results(P0_TestCases.java:218)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)at org.testng.internal.Invoker.invokeMethod(Invoker.java:634)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)at java.util.concurrent.FutureTask.run(Unknown Source)at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)at java.lang.Thread.run(Unknown Source)]]>
    </error>
  </testcase> <!-- results -->
</testsuite> <!-- AutomationSuites.nativeApp.P0_TestCases -->
